# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc2a8b951b6b0e99aedd48dcd9689ad33f6b2b569bf2e3bcf7608f067a8b5bb2d88d6811a454110a4beb6cd916f4b7fd8fd5373b7ab982292e8a614c1be3e4a7

test:
  secret_key_base: 2615ccc8152793600322fa7f861718bc865b1419216e5a6b824daf27bb04b34b68fe0add1f23b580a957c3d915cc2a8cb8d3c44bbff6d49ea0c258f52242fbdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
